In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("superstore_dataset.csv")
df.head()

,Order ID,Order Date,Ship Date,Customer Name,Segment,Region,Category,Sales,Quantity,Discount,Profit
0,ORD-1000,2023-01-01,2023-01-03,Customer 0,Home Office,South,Furniture,690.15,1,0.16,42.29
1,ORD-1001,2023-01-02,2023-01-04,Customer 1,Consumer,East,Furniture,446.86,5,0.02,43.27
2,ORD-1002,2023-01-03,2023-01-05,Customer 2,Home Office,West,Technology,713.45,4,0.07,206.26
3,ORD-1003,2023-01-04,2023-01-06,Customer 3,Home Office,East,Furniture,406.56,8,0.16,37.76
4,ORD-1004,2023-01-05,2023-01-07,Customer 4,Consumer,West,Technology,334.63,1,0.13,171.58

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order ID       200 non-null    object
 1   Order Date     200 non-null    object
 2   Ship Date      200 non-null    object
 3   Customer Name  200 non-null    object
 4   Segment        200 non-null    object
 5   Region         200 non-null    object
 6   Category       200 non-null    object
 7   Sales          200 non-null    float64
 8   Quantity       200 non-null    int64
 9   Discount       200 non-null    float64
 10  Profit         200 non-null    float64
dtypes: float64(3), int64(1), object(7)
memory usage: 17.3+ KB

In [4]:
df.describe()

            Sales    Quantity    Discount      Profit
count  200.000000  200.000000  200.000000  200.000000
mean   560.137500    5.020000    0.154700  130.624650
std    254.252904    2.616069    0.081727  104.922653
min    112.300000    1.000000    0.000000  -49.920000
25%    341.192500    3.000000    0.090000   44.935000
50%    555.170000    5.000000    0.160000  132.865000
75%    767.607500    7.000000    0.230000  216.700000
max    996.340000    9.000000    0.300000  299.770000

In [5]:
df.isnull().sum()

Order ID         0
Order Date       0
Ship Date        0
Customer Name    0
Segment          0
Region           0
Category         0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

In [6]:
df.duplicated().sum()

np.int64(0)

In [7]:
df = df.drop_duplicates()

In [8]:
df['Order Date'] = pd.to_datetime(df['Order Date'])
df['Ship Date'] = pd.to_datetime(df['Ship Date'])

In [9]:
df.columns = df.columns.str.strip()

In [10]:
df['Year'] = df['Order Date'].dt.year
df['Month'] = df['Order Date'].dt.month

In [11]:
df['Profit Margin'] = df['Profit'] / df['Sales']

In [12]:
df.to_csv("cleaned_superstore.csv", index=False)